logLevel: 'info'
database:
  host: localhost
  port: 5984
  database: hacktoberfest
  username: hacktoberfest
  password: hacktoberfest
oauth:
  clientId: ''
  clientSecret: ''
  scopes: ['user']
server:
  port: 5353
  domain: 'example.com'
  sessionKey: 'enter a random key here'
