logLevel: 'info'
database:
  host: localhost
  port: 5432
  database: postgres
  username: postgres
  password: postgres
oauth:
  clientId: ''
  clientSecret: ''
  scopes: ['user']
server:
  port: 5353
  domain: 'example.com'
  sessionKey: 'enter a random key here'
