version: "3.7"
services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: hacktoberfest
      MONGO_INITDB_ROOT_PASSWORD: hacktoberfest
      MONGO_INITDB_DATABASE: hacktoberfest
    ports:
      - '27017:27017'
  hacktoberfest:
    build:
      context: .
    ports:
      - '5353:5353'
    depends_on:
      - db
volumes:
  hacktoberfest-db:
